import {validateTransitionPolicy} from './transition_policy.js';
import {writingPolicy} from './writing_evaluation.js';
export const ACTIVITY_TYPES=Object.freeze(['meaning_choice','listening_choice','listening_action','echo','speaking_from_meaning','interaction','reading_meaning','writing_short_answer','writing_dictation','writing_sentence_build','continuous_listening','review_probe']);
const CAPS=new Set(['R','L','S','W','A','ECHO']);
const COMMON=new Set(['activity_id','type','capability','input','task','support_policy','evidence_policy','repair_policy','completion_policy','transition_policy','review_policy','evaluation_policy','interaction','next','extensions']);
const SPEAKING_BOOL=['active_generation','listener_required','blind_listener_required','self_check_allowed'];
const ALLOWED_SUPPORT=new Set(['replay','clear_support','slow_support','text_support','answer_help','meaning_hint']);
const IMAGE_EXT=/\.(png|webp|jpe?g)$/i,AUDIO_EXT=/\.(wav|mp3|m4a|aac)$/i,TEXT_EXT=/\.(txt|json)$/i;
function obj(v){return v&&typeof v==='object'&&!Array.isArray(v);}
function req(cond,msg='课程活动配置不完整。'){if(!cond)throw Error(msg);}
function uniqueOptions(options,{noEnglishLabels=false}={}){req(Array.isArray(options)&&options.length>=2,'选项配置无效。');const vals=new Set();for(const o of options){req(obj(o)&&typeof o.value==='string'&&o.value&& !vals.has(o.value),'选项配置无效。');vals.add(o.value);req(typeof o.label==='string'||typeof o.image==='string','选项缺少显示内容。');if(noEnglishLabels&&typeof o.label==='string'&&/[A-Za-z]/.test(o.label))throw Error('Speaking私有意义选项不能显示英文答案。');}return vals;}
function validateSupport(a){req(obj(a.support_policy)&&Array.isArray(a.support_policy.allowed),'support_policy 无效。');for(const x of a.support_policy.allowed)req(ALLOWED_SUPPORT.has(x),'未知帮助类型。');if(a.support_policy.allowed.includes('answer_help'))req(typeof a.support_policy.hint==='string'&&a.support_policy.hint.trim(),'answer_help 必须声明提示。');}
function validateCompletion(a){req(obj(a.completion_policy),'completion_policy 无效。');const n=a.completion_policy.max_attempts??3;req(Number.isInteger(n)&&n>=1&&n<=6,'max_attempts 无效。');}
function validateSpeakingPolicy(a){req(obj(a.evidence_policy),'Speaking evidence_policy 缺失。');for(const k of SPEAKING_BOOL)req(typeof a.evidence_policy[k]==='boolean','Speaking evidence_policy 缺少布尔字段。');req(a.evidence_policy.listener_required===true&&a.evidence_policy.blind_listener_required===true,'本代Speaking需要盲听协议。');}
function validateWriting(a){writingPolicy(a);if(a.type==='writing_sentence_build'){req(Array.isArray(a.task.pieces)&&a.task.pieces.length>=2&&a.task.pieces.every(x=>typeof x==='string'&&x.trim()),'句块Writing配置无效。');}}
function validateReview(a){req(['R','L','S','W','A'].includes(a.capability),'review_probe capability 无效。');if(a.capability==='S'){validateSpeakingPolicy(a);uniqueOptions(a.task.options,{noEnglishLabels:true});req(typeof a.task.prompt==='string'&&a.task.prompt.trim(),'Speaking review缺少prompt。');}if(a.capability==='W')validateWriting(a);if(a.capability==='L'){req(typeof a.input.audio_id==='string','Listening review缺少音频。');uniqueOptions(a.task.options);req(a.task.answer!==undefined,'Listening review缺少answer。');}}
export function validateActivity(a){req(obj(a)&&typeof a.activity_id==='string'&&/^[A-Za-z0-9_.:-]{1,80}$/.test(a.activity_id),'activity_id 无效。');req(ACTIVITY_TYPES.includes(a.type)&&CAPS.has(a.capability),'Activity type/capability 无效。');for(const k of Object.keys(a))req(COMMON.has(k),'未知Activity执行字段。');req(obj(a.input)&&obj(a.task)&&obj(a.evidence_policy)&&obj(a.repair_policy),'课程活动配置不完整。');validateSupport(a);validateCompletion(a);a.transition_policy=validateTransitionPolicy(a.transition_policy);
 let vals;
 switch(a.type){
  case 'meaning_choice':req(['A','R'].includes(a.capability),'meaning_choice capability 无效。');vals=uniqueOptions(a.task.options);req(vals.has(String(a.task.answer)),'meaning_choice answer 无效。');if(a.capability==='R')req(typeof a.input.text==='string'||typeof a.input.text_resource==='string','Reading meaning缺少文本。');break;
  case 'listening_choice':req(a.capability==='L','listening_choice必须L。');req(typeof a.input.audio_id==='string','Listening缺少audio_id。');vals=uniqueOptions(a.task.options);req(vals.has(String(a.task.answer)),'Listening answer 无效。');break;
  case 'listening_action':req(a.capability==='L','listening_action必须L。');req(typeof a.input.audio_id==='string','Listening缺少audio_id。');vals=uniqueOptions(a.task.options);req(vals.has(String(a.task.answer)),'Listening action无效。');break;
  case 'echo':req(a.capability==='ECHO','echo必须ECHO。');req(typeof a.input.audio_id==='string','Echo缺少audio_id。');req(a.evidence_policy.active_generation!==true,'Echo不能声明主动Speaking。');break;
  case 'speaking_from_meaning':req(a.capability==='S','speaking_from_meaning必须S。');validateSpeakingPolicy(a);vals=uniqueOptions(a.task.options,{noEnglishLabels:true});req(typeof a.task.prompt==='string','Speaking缺少prompt。');break;
  case 'interaction':req(a.capability==='S','interaction必须S。');validateSpeakingPolicy(a);req(Array.isArray(a.task.allowed_actions)&&a.task.allowed_actions.length>=2&&new Set(a.task.allowed_actions).size===a.task.allowed_actions.length,'Interaction actions无效。');req(obj(a.interaction)||Array.isArray(a.task.turns),'Interaction turns缺失。');{const turns=a.interaction?.turns||a.task.turns;req(Array.isArray(turns)&&turns.length>=2,'Interaction至少两轮。');const ids=new Set();for(const t of turns){req(obj(t)&&typeof t.turn_id==='string'&&!ids.has(t.turn_id)&&typeof t.prompt==='string','Interaction turn无效。');ids.add(t.turn_id);req(obj(t.intent_policy),'Interaction intent_policy缺失。');if(Array.isArray(t.intent_policy.options))uniqueOptions(t.intent_policy.options,{noEnglishLabels:true});}}break;
  case 'reading_meaning':req(a.capability==='R','reading_meaning必须R。');req(typeof a.input.text==='string'||typeof a.input.text_resource==='string','Reading缺少文本。');vals=uniqueOptions(a.task.options);req(vals.has(String(a.task.answer)),'Reading answer无效。');break;
  case 'writing_short_answer':req(a.capability==='W','writing_short_answer必须W。');validateWriting(a);break;
  case 'writing_dictation':req(a.capability==='W','writing_dictation必须W。');req(typeof a.input.audio_id==='string','Dictation缺少音频。');validateWriting(a);break;
  case 'writing_sentence_build':req(a.capability==='W','writing_sentence_build必须W。');validateWriting(a);break;
  case 'continuous_listening':req(a.capability==='L','continuous_listening必须L。');req(typeof a.input.audio_id==='string','Continuous Listening缺少音频。');break;
  case 'review_probe':validateReview(a);break;
 }
 return a;
}
export function validateActivities(list){req(Array.isArray(list)&&list.length&&list.length<=240,'课程活动配置不完整。');const ids=new Set();for(const a of list){validateActivity(a);req(!ids.has(a.activity_id),'activity_id重复。');ids.add(a.activity_id);}for(const a of list)req(a.next===null||typeof a.next==='string'&&ids.has(a.next),'课程活动衔接不完整。');return list;}
export function initialDomain(a){if(a.type.startsWith('listening')||a.type==='continuous_listening')return 'listening_active';if(a.capability==='S'||a.type==='echo')return 'speaking_ready';return 'meaning_ready';}
function pushRef(out,kind,value,where){if(typeof value==='string'&&value)out.push({kind,value,where});}
export function collectResourceRefs(a){const out=[];for(const k of ['audio_id','natural_audio_id','clear_audio_id'])pushRef(out,'audio',a.input?.[k],`input.${k}`);pushRef(out,'text',a.input?.text_resource,'input.text_resource');pushRef(out,'image',a.input?.image,'input.image');for(const [i,o] of (a.task?.options||[]).entries())pushRef(out,'image',o.image,`task.options[${i}].image`);const turns=a.interaction?.turns||a.task?.turns||[];for(const [i,t] of turns.entries()){pushRef(out,'audio',t.input?.audio_id,`turns[${i}].input.audio_id`);pushRef(out,'image',t.input?.image,`turns[${i}].input.image`);for(const [j,o] of (t.intent_policy?.options||[]).entries())pushRef(out,'image',o.image,`turns[${i}].intent_policy.options[${j}].image`);}pushRef(out,'audio',a.support_policy?.clear_audio_id,'support_policy.clear_audio_id');pushRef(out,'image',a.support_policy?.image,'support_policy.image');return out;}
export function validateResourceGraph(config,audioManifest,manifestFiles){if(config.lesson_engine!=='activity-v1')return true;validateActivities(config.activities);req(Array.isArray(audioManifest),'音频清单无效。');const fileMap=new Map(manifestFiles.map(f=>[f.path,f]));const audioMap=new Map();for(const x of audioManifest){req(obj(x)&&typeof x.audio_id==='string'&&!audioMap.has(x.audio_id)&&typeof x.file_name==='string','音频清单无效。');const f=fileMap.get(x.file_name);req(f&&AUDIO_EXT.test(x.file_name),'音频类型或路径无效。');if(x.sha256)req(x.sha256===f.sha256,'音频SHA声明冲突。');audioMap.set(x.audio_id,x);}
 for(const a of config.activities)for(const r of collectResourceRefs(a)){if(r.kind==='audio')req(audioMap.has(r.value),'Activity音频引用悬空。');else if(r.kind==='image'){const f=fileMap.get(r.value);req(f&&IMAGE_EXT.test(r.value),'Activity图片引用无效。');}else if(r.kind==='text'){const [path,frag]=r.value.split('#');const f=fileMap.get(path);req(f&&TEXT_EXT.test(path),'Activity文本引用无效。');if(frag)req(/^[A-Za-z0-9_.-]+$/.test(frag),'text_resource fragment无效。');}}
 if(config.optional_resource_packs?.some(x=>x?.required===true))throw Error('unsupported_dependency');return true;}
