import {ContinuousListening} from './learning_extensions.js';
import {activityEngine as engine} from './activity_engine.js';
import {runtime} from './local_runtime.js';
import {registry} from './registry.js';
import {storage} from './storage.js';
import {MediaPlayer} from './media.js';
import {Recorder} from './recorder.js';
import {HumanListenerBridge} from './human_listener.js';
import {effectiveVisible} from './transition_policy.js';
const sid=new URL(location.href).searchParams.get('session'),root=document.getElementById('activity');let model,busy=false,url=null,timer=null,generation=0;
const player=new MediaPlayer(),rec=new Recorder(),listener=new HumanListenerBridge();let loops=1;const continuous=new ContinuousListening(player);const call=(cmd,d={})=>engine.request(sid,cmd,d);
function el(tag,value=''){const e=document.createElement(tag);e.textContent=value;root.append(e);return e;}
function button(label,fn,primary=true){const b=el('button',label);b.className=primary?'primary':'quiet';b.onclick=async()=>{if(busy)return;busy=true;try{await fn();}catch(err){root.replaceChildren();el('h1','再试一次');el('p',err?.message||'当前步骤未完成');button('再试一次',render);button('返回课程',()=>{location.href='./'},false);}finally{busy=false;}};return b;}
async function asset(path){return (await registry.response(model.session.unit_id,path,sid)).blob();}
async function playBlob(blob,id,rate=1){if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(blob);player.make=()=>{const a=new Audio();a.playbackRate=rate;return a;};if(model.activity?.type==='continuous_listening')await continuous.play(url,{loops,profile:{playback_rate:rate,variant:model.run.audio_profile?.variant||'clear_natural'}});else await player.play(url,{id,manual:true});}
async function playCourse(){const m=await(await registry.response(model.session.unit_id,'audio_manifest.json',sid)).json(),a=m.find(x=>x.audio_id===(model.run.audio_id||model.turn?.input?.audio_id||model.activity.input.audio_id));if(!a)throw Error('这段声音需要重新连接。');await playBlob(await asset(a.file_name),a.audio_id,model.run.audio_profile?.playback_rate||1);await call('audio_played',{play_count:model.activity.type==='continuous_listening'?continuous.plays:1});await render();}
function cueOptions(){const a=model.activity,run=model.run;return a.type==='interaction'?(model.turn?.intent_policy?.options||[]):(a.task.options||[]);}
function showCue(option){if(!option?.image)return;const img=document.createElement('img');img.src='./units/'+model.session.unit_id+'/s/'+sid+'/'+option.image;img.alt='';root.append(img);}
async function feedbackReady(){const imgs=[...root.querySelectorAll?.('img')||[]];for(const img of imgs){try{if(img.decode)await img.decode();else if(!img.complete)await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;});}catch{throw Error('反馈图片没有加载完成。');}}await call('feedback_presented',{monotonic_now:performance.now()});}
async function driveTransition(myGen){model=await call('state');const t=model.session.transition;if(!t||t.completed||myGen!==generation)return;await feedbackReady();model=await call('state');const x=model.session.transition;if(!x||myGen!==generation)return;const remaining=Math.max(0,x.min_dwell_ms-effectiveVisible(x,performance.now()));const go=async trigger=>{if(myGen!==generation)return;await call('advance',{token:x.token,trigger,monotonic_now:performance.now()});await render();};if(x.mode==='auto'&&remaining===0)return go('auto');if(x.mode==='auto_after_ms'){timer=setTimeout(()=>go('auto').catch(()=>render()),remaining);}if(x.allow_manual_continue){const b=button('继续',()=>go('manual'));if(remaining>0){b.disabled=true;timer=setTimeout(()=>{if(myGen===generation)b.disabled=false;},remaining);}}}
async function render(){generation++;const myGen=generation;if(timer){clearTimeout(timer);timer=null;}model=await call('state');root.replaceChildren();const {session:s,activity:a,run,turn}=model;if(s.status==='completed'){rec.closeStream();player.release();el('h1','完成');button('返回课程',()=>{location.href='./'});return;}
 if(s.listener_handoff_pending){el('h1','已回应');el('p','请把设备交还学习者。');button('继续学习',async()=>{await call('listener_handoff_complete');await render();});return;}
 if(s.current_domain_state==='evidence_settled'){el('h1',run.last_evidence?.correct===true?'已完成':'这次还没完成');if(run.last_evidence?.evidence_class==='supported')el('p','这次用了帮助，系统会安排后续巩固。');return driveTransition(myGen);}
 const intent= a.type==='interaction'?run.turn_intent:run.private_choice;
 if(a.capability==='S'&&intent===undefined){el('h1',turn?.prompt||a.task.prompt||'先从自己的意思开始');const options=cueOptions();for(const o of options){const b=button(o.label||'选择',async()=>{await call('intent',{value:o.value});await render();},false);if(o.image){const img=document.createElement('img');img.src='./units/'+s.unit_id+'/s/'+sid+'/'+o.image;img.alt='';b.replaceChildren(img);}}return;}
 if(intent!==undefined)showCue(cueOptions().find(x=>x.value===intent));el('h1',turn?.prompt||a.task.prompt||({W:'写一下',S:'说出来',L:'听一下',ECHO:'跟着说一次'}[a.capability]||'选一个'));
 const attempt=s.attempts.find(x=>x.attempt_id===s.pending_attempt_id&&!x.result);
 if(s.current_domain_state==='listener_pending'){
  const media=await storage.get('media',attempt?.attempt_id);if(!attempt||!media?.blob){await runtime.request('recover',{_session_id:sid});return render();}
  button('让对方听',async()=>{const bind=await call('listener_open');const result=await listener.open({audioBlob:media.blob,receipt:bind.receipt,allowed_actions:bind.allowed_actions});await call('listener_result',{attempt_id:bind.attempt_id,ticket:bind.ticket,...result});await render();});
  if(a.evidence_policy?.self_check_allowed)button('自己核对（不算独立口语）',async()=>{const bind=await call('listener_open');const action=prompt('自己实际听到后选择行动：'+bind.allowed_actions.join(' / '));await call('self_result',{attempt_id:bind.attempt_id,ticket:bind.ticket,action});await render();},false);return;
 }
 if(s.current_domain_state==='recording_complete'||s.current_domain_state==='playback_ready'){
  const media=await storage.get('media',attempt?.attempt_id);if(!media?.blob){await runtime.request('recover',{_session_id:sid});return render();}button('听听自己',async()=>{await playBlob(media.blob,'own-voice');await call('self_playback');await render();});return;
 }
 if(a.type==='continuous_listening'){const select=document.createElement('select');for(const count of [1,3,5]){const o=document.createElement('option');o.value=count;o.textContent=count+'次';select.append(o);}select.value=loops;select.onchange=()=>loops=Number(select.value);root.append(select);const transcript=el('p','');if(a.input.text)button('看一下文字',async()=>{continuous.toggleText(!continuous.text_visible);transcript.textContent=continuous.text_visible?a.input.text:'';if(continuous.text_visible)await call('support',{kind:'text_support'});},false);if(run.audio_completed&&!a.task.options?.length){button('完成这次连续听',async()=>{await call('exposure_complete');await render();});return;}}
 if((a.input.audio_id||turn?.input?.audio_id)&&!run.audio_completed){button('听一下',playCourse);return;}
 if(['S','ECHO'].includes(a.capability)){const b=button('点一下开始',async()=>{if(rec.state==='idle'){await rec.start();await call('recording_start');b.textContent='点一下结束';}else if(rec.state==='recording'){let data;try{data=await rec.stop();}finally{rec.closeStream();}await call('record',data);await render();}});return;}
 if(a.capability==='W'){let value='';if(a.type==='writing_sentence_build'){const line=el('p','');for(const word of a.task.pieces||[])button(word,()=>{value+=(value?' ':'')+word;line.textContent=value;},false);button('重新排列',()=>{value='';line.textContent='';},false);}else{const input=document.createElement('textarea');input.autocomplete='off';input.oninput=()=>value=input.value;root.append(input);}button('写好了',async()=>{await call('answer',{value});await render();});}
 else for(const c of a.task.options||[]){const b=button(c.label||'选一个',async()=>{await call('answer',{value:c.value});await render();},false);if(c.image){const img=document.createElement('img');img.src='./units/'+s.unit_id+'/s/'+sid+'/'+c.image;img.alt='';b.replaceChildren(img);}}
 if(a.input.audio_id)button('再听一次',playCourse,false);if(a.support_policy.allowed?.length)button('帮一下',async()=>{await call('support',{kind:a.support_policy.allowed[0]});await render();},false);
}
window.addEventListener('pagehide',()=>{listener.close('pagehide');rec.cancel();player.release();if(url)URL.revokeObjectURL(url);if(model?.session?.transition)call('feedback_visibility',{visible:false,monotonic_now:performance.now()}).catch(()=>{});});document.addEventListener('visibilitychange',()=>{if(document.hidden){listener.close('hidden');rec.cancel();player.stop();if(model?.session?.transition)call('feedback_visibility',{visible:false,monotonic_now:performance.now()}).catch(()=>{});}else{call('feedback_visibility',{visible:true,monotonic_now:performance.now()}).catch(()=>{}).finally(()=>runtime.request('recover',{_session_id:sid}).then(render).catch(()=>{}));}});
try{await runtime.request('recover',{_session_id:sid});model=await call('state');if(model.session.status==='new')await call('start');await render();}catch{root.replaceChildren();el('h1','请从课程目录继续');button('返回课程',()=>{location.href='./'});}
