const SAFE_STATUS=new Set(['new','active','interrupted','completed','abandoned','speaking_ready','recording_active','recording_complete','listener_pending','repair_needed','evidence_settled','session_completed','meaning_ready','listening_active']);
const SAFE_TYPES=new Set(['meaning_choice','listening_choice','listening_action','echo','speaking_from_meaning','interaction','reading_meaning','writing_short_answer','writing_dictation','writing_sentence_build','continuous_listening','review_probe']);
const SAFE_CAP=new Set(['R','L','S','W','A','ECHO']);
const str=(v,n=120)=>typeof v==='string'?v.slice(0,n):null;
function safeStatus(v){return SAFE_STATUS.has(v)?v:null;}
function safeType(v){return SAFE_TYPES.has(v)?v:null;}
function safeCap(v){return SAFE_CAP.has(v)?v:null;}
function alias(id,prefix='a'){if(!id)return null;let h=2166136261;for(const c of String(id)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return prefix+'_'+(h>>>0).toString(16).padStart(8,'0');}
export function projectSession(s={}){const runs={};for(const [id,r] of Object.entries(s.activity_runs||{}))runs[id]={activity_id:id,type:safeType(r.type),status:safeStatus(r.status||s.current_domain_state),turn_index:Number.isInteger(r.turn_index)?r.turn_index:null,attempt_count:Number.isInteger(r.attempt_index)?r.attempt_index:Array.isArray(r.attempts)?r.attempts.length:null,settled:!!r.last_evidence,media_present:!!r.media_present};return {session_id:alias(s.session_id,'s'),unit_id:str(s.unit_id,16),session_kind:s.session_kind==='review'?'review':'lesson',status:safeStatus(s.status),current_activity_id:str(s.current_activity_id,64),current_domain_state:safeStatus(s.current_domain_state),last_safe_checkpoint:str(s.last_safe_checkpoint,64),revision:Number.isInteger(s.revision)?s.revision:0,activity_runs:runs,attempts:(s.attempts||[]).map(a=>({attempt_alias:alias(a.attempt_id),activity_id:str(a.activity_id,64),turn_index:Number.isInteger(a.turn_index)?a.turn_index:null,attempt_index:Number.isInteger(a.attempt_index)?a.attempt_index:null,mode:safeCap(a.mode),settled:!!a.result,audio_deleted:!!a.audio_deleted,duration_ms:Number.isFinite(a.duration)?Math.round(a.duration*1000):null})),transition:s.transition?{activity_id:str(s.transition.activity_id,64),mode:['auto','auto_after_ms','continue_button'].includes(s.transition.mode)?s.transition.mode:null,visible_elapsed_ms:Number.isFinite(s.transition.visible_elapsed_ms)?Math.round(s.transition.visible_elapsed_ms):0,feedback_ready:!!s.transition.feedback_ready,completed:!!s.transition.completed}:null,updated_at:Number.isFinite(s.updated_at)?s.updated_at:null};}
export function projectReview(r={}){return {id:alias(r.id,'r'),unit_id:str(r.unit_id,16),activity_id:str(r.activity_id,64),modality:safeCap(r.modality),reason:['listening_failed','speaking_retrieval_failed','writing_failed','delayed_forgetting','slow_dependency','text_dependency','transfer_failed','recurring_error'].includes(r.reason)?r.reason:null,status:['due','future','resolved','blocked'].includes(r.status)?r.status:null,due_at:Number.isFinite(r.due_at)?r.due_at:null,failure_count:Number.isInteger(r.failure_count)?r.failure_count:0,generation:Number.isInteger(r.generation)?r.generation:1};}
export function projectEvent(e={}){const allowedType=['ACTIVITY_RESULT','REPAIR','NATURAL_RETEST','safe_recovery_used','PILOT_START','PILOT_END','FINAL_EVIDENCE_SETTLED','S_RESULT','L_ACTION','sw_ready'].includes(e.evidence_type)?e.evidence_type:'event';return {id:alias(e.id,'e'),evidence_type:allowedType,unit_id:str(e.unit_id,16),activity_id:str(e.activity_id,64),modality:safeCap(e.modality||e.capability),timestamp:Number.isFinite(e.timestamp)?e.timestamp:null,error_code:/^[A-Z0-9_:-]{1,64}$/.test(e.error_code||'')?e.error_code:null,correct:typeof e.correct==='boolean'?e.correct:null,independent:typeof e.independent==='boolean'?e.independent:null,support_level:['independent','supported','answer_help','unknown'].includes(e.support_level)?e.support_level:null};}
export function projectRegistry(r={}){return {unit_id:str(r.unit_id,16),version:str(r.version,32),install_state:['installed','updating','repair_needed','missing_assets'].includes(r.install_state)?r.install_state:null,offline_ready:!!r.offline_ready,lesson_engine:['u01-frozen-v1','activity-v1'].includes(r.lesson_engine)?r.lesson_engine:null,build:str(r.build,64)};}
