import {resolveReviewPolicy} from './review_policy.js';
export const SENTENCE_LEVELS=['whole_situation','task_meaning','key_information','meaning_chunks','variation','prediction','active_response','whole_independent_understanding'];
export function sentenceStep(example,level){if(!SENTENCE_LEVELS.includes(level))throw Error('理解步骤无效。');return {level,content:example[level],whole:example.whole};}
export function resolveMeaning(network,lexeme,context){const word=network.find(x=>x.lexeme===lexeme),node=word?.meanings.find(x=>x.contexts.includes(context));return node?{meaning_id:node.meaning_id,explanation:node.explanation,collocations:node.collocations,examples:node.examples,audio:node.audio,pattern:node.pattern,usage_boundary:node.usage_boundary}:null;}
export const REVIEW_REASONS=['listening_failed','speaking_retrieval_failed','writing_failed','delayed_forgetting','slow_dependency','text_dependency','transfer_failed','recurring_error'];
const reasonFor=e=>{if(e.delayed_test&&e.correct===false)return ['delayed_forgetting',105];if(e.transfer_context&&e.correct===false)return ['transfer_failed',105];if(e.modality==='L'&&e.correct===false)return ['listening_failed',100];if(e.modality==='S'&&e.correct===false&&e.activity_type!=='echo')return ['speaking_retrieval_failed',100];if(e.modality==='W'&&e.correct===false)return ['writing_failed',90];if(e.playback_rate>0&&e.playback_rate<1)return ['slow_dependency',95];if(e.text_visible&&e.modality==='L')return ['text_dependency',95];return null;};
const targetFor=e=>String(e.language_item_id||e.target_action||e.target||e.meaning_target||'general').replace(/[^A-Za-z0-9_.:-]/g,'_').slice(0,80);
export const reviewKey=e=>[e.unit_id,e.source_activity_id||e.activity_id,e.modality||e.capability,targetFor(e)].join(':');
function isResolving(e){return e.correct===true&&e.independent===true&&e.playback_rate!==.85&&e.text_visible!==true;}
export function practiceSchedule(evidence,now=Date.now()){const map=new Map();for(const e of [...evidence].sort((a,b)=>(a.timestamp||0)-(b.timestamp||0)||String(a.id||'').localeCompare(String(b.id||'')))){const key=reviewKey(e),prev=map.get(key),stamp=Number(e.timestamp||now),eventGen=Number(e.review_generation||0);if(prev&&stamp<prev.generation_started_at)continue;if(prev&&eventGen>0&&eventGen<prev.generation)continue;if(isResolving(e)){if(prev&&(!eventGen||eventGen===prev.generation)){prev.status='resolved';prev.resolved_at=stamp;prev.last_event_id=e.id||null;}continue;}const r=reasonFor(e);if(!r)continue;const [reason,priority]=r,policy=resolveReviewPolicy(e.activity_snapshot||{});if(prev&&prev.status!=='resolved'){prev.reason=reason;prev.priority=Math.max(prev.priority,priority);prev.failure_count++;prev.last_event_id=e.id||null;if(eventGen>0){prev.generation=Math.max(prev.generation+1,eventGen+1);prev.generation_started_at=stamp;prev.due_at=stamp+(e.review_immediate?0:policy.retry_after_ms);prev.review_policy_version=policy.version;}continue;}map.set(key,{id:'practice:'+key,unit_id:e.unit_id,activity_id:e.source_activity_id||e.activity_id,source_activity_id:e.source_activity_id||e.activity_id,modality:e.modality||e.capability,target_key:targetFor(e),reason,priority,due_at:stamp+(e.review_immediate?0:policy.retry_after_ms),failure_count:(prev?.failure_count||0)+1,generation:(prev?.generation||0)+1,generation_started_at:stamp,status:'future',required_condition:['slow_dependency','text_dependency'].includes(reason)?'natural_1_no_text':'independent_probe',review_policy_version:policy.version,last_event_id:e.id||null});}for(const x of map.values())if(x.status!=='resolved')x.status=x.due_at<=now?'due':'future';return [...map.values()].sort((a,b)=>b.priority-a.priority||a.due_at-b.due_at);}
export async function updateReview(db,now=Date.now()){const events=[];for await(const row of db.iterate('events'))if(row.evidence_type==='ACTIVITY_RESULT'||['L_ACTION','S_RESULT'].includes(row.evidence_type))events.push(row);const projected=practiceSchedule(events,now),wanted=new Set(projected.map(x=>x.id)),ops=[];const existing=[];for await(const r of db.iterate('review'))if(r.id.startsWith('practice:'))existing.push(r);for(const r of existing)if(!wanted.has(r.id))ops.push({store:'review',id:r.id,delete:true});for(const j of projected)ops.push({store:'review',value:j});if(ops.length)await db.batch(ops);return projected;}
export async function dueReview(db,now=Date.now()){await updateReview(db,now);const out=[];for await(const r of db.iterate('review'))if(r.status!=='resolved'&&r.due_at<=now)out.push({...r,status:'due'});return out.sort((a,b)=>b.priority-a.priority||a.due_at-b.due_at);}
export class ContinuousListening{constructor(player,emit=()=>{}){this.player=player;this.emit=emit;this.generation=0;this.plays=0;this.text_visible=false;}async play(src,{loops=1,profile={playback_rate:1,variant:'clear_natural',support_level:'independent'}}={}){if(![1,3,5].includes(loops))throw Error('请选择播放次数。');const gen=++this.generation;this.plays=0;this.profile={...profile};for(let i=0;i<loops;i++){await this.player.play(src,{id:'continuous',manual:i===0});if(gen!==this.generation)return;this.plays++;this.emit('continuous_played',this.conditions());}return this.conditions();}toggleText(show){this.text_visible=!!show;this.text_seen ||= !!show;this.emit('continuous_text',{text_visible:this.text_visible});}conditions(){return {play_count:this.plays,text_visible:this.text_visible,text_seen:!!this.text_seen,playback_rate:this.profile?.playback_rate??1,audio_variant:this.profile?.variant||null,support_level:this.profile?.support_level||'independent'};}stop(){this.generation++;this.player.stop();}}
