import {storage} from './storage.js';import {UnitInstaller,INSTALLED} from './packages.js';import {exportState,restoreProgress} from './transfer.js';
const $=id=>document.getElementById(id),installer=new UnitInstaller();let ready=false;
async function refresh(){const installed=await storage.get('critical',INSTALLED);$('course').textContent=installed?'已安装课程：U01 Day1':'还没有导入课件';$('start').hidden=!installed;}
async function guard(fn){try{await fn()}catch(e){$('status').textContent=e.message;}}
async function waitForController(ms=3500){if(navigator.serviceWorker.controller)return true;return await new Promise(resolve=>{let done=false;const finish=v=>{if(done)return;done=true;clearTimeout(t);navigator.serviceWorker.removeEventListener('controllerchange',changed);resolve(v)};const changed=()=>finish(true);const t=setTimeout(()=>finish(!!navigator.serviceWorker.controller),ms);navigator.serviceWorker.addEventListener('controllerchange',changed);});}
async function prepareOffline(){if(!globalThis.isSecureContext||!navigator.serviceWorker)throw Error('请从GitHub Pages的HTTPS网址打开。');$('status').textContent='正在准备离线使用…';const reg=await navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'});try{await reg.update()}catch{}await navigator.serviceWorker.ready;let controlled=await waitForController();if(!controlled&&navigator.onLine&&!sessionStorage.getItem('english_sw_reload_once')){sessionStorage.setItem('english_sw_reload_once','1');location.reload();return false;}if(controlled){sessionStorage.removeItem('english_sw_reload_once');ready=true;$('status').textContent='已准备好。';return true;}ready=false;$('status').textContent=navigator.onLine?'离线准备还在进行，请保持联网稍等几秒。':'首次离线准备尚未完成，请联网打开一次。';return false;}
$('import').onclick=()=>$('package').click();$('package').onchange=()=>guard(async()=>{const f=$('package').files[0];if(!f)return;$('import').disabled=true;try{$('status').textContent='正在检查并安装，请稍等。';await installer.install(f);await refresh();$('status').textContent=ready?'课件已安装，可以开始学习。':'课件已安装；正在准备离线使用。';}finally{$('import').disabled=false;$('package').value='';}});
$('start').onclick=()=>guard(async()=>{if(!ready||!navigator.serviceWorker.controller){if(!navigator.onLine)throw Error('首次离线准备尚未完成，请联网打开一次。');const ok=await prepareOffline();if(!ok)return;}location.href='./lesson.html';});
$('backup').onclick=()=>guard(exportState);$('restore').onchange=()=>guard(async()=>{const f=$('restore').files[0];if(f){const r=await restoreProgress(f);$('status').textContent=r.interrupted_audio?'进度已恢复；中断且无原音的那次说话需要重试。':'进度已恢复。';}});
guard(async()=>{await refresh();await prepareOffline();});
