import {registry} from './registry.js';
import {BUILD} from './build.js';
const BASE=new URL('./',self.registration.scope),SHELL='english-shell-'+BUILD;
const FILES=["./activity.html","./activity_engine.js","./activity_protocol.js","./activity_renderer.js","./activity_validation.js","./app.js","./audio_profile.js","./base.js","./blind_panel.html","./build.js","./cache_gc.js","./core.js","./course_lock.js","./diagnostic.js","./diagnostic_redaction.js","./evidence.js","./generic_listener.html","./hold.js","./human_listener.js","./icons/icon.png","./icons/icon.svg","./index.html","./learning_extensions.js","./legacy_u01.js","./lesson.html","./library.js","./listener_adapter.js","./local_runtime.js","./manifest.json","./media.js","./packages.js","./pilot.html","./pilot.js","./practice.js","./progress_pointer.js","./recorder.js","./registry.js","./resume.js","./review_policy.js","./shell.js","./storage.js","./style.css","./theme.js","./transfer.js","./transition_policy.js","./transport.js","./u01_adapter.js","./ux_policy.js","./vendor/LICENSE_JSZIP.txt","./vendor/jszip.min.js","./version.json","./writing_evaluation.js"];
self.addEventListener('install',e=>e.waitUntil(caches.open(SHELL).then(c=>c.addAll(FILES.map(p=>new Request(new URL(p,BASE).href,{cache:'reload'}))))));
self.addEventListener('activate',e=>e.waitUntil((async()=>{await self.clients.claim();const obsolete=['english-shell-pages-v1','english-shell-pages-v1-audio-fix-1','english-shell-1.1.0-rc.1','english-shell-1.1.0-rc.2','english-shell-1.1.0-rc.3','english-shell-1.1.0-rc.4','english-shell-1.1.0-rc.5','english-shell-1.1.0-rc.6','english-shell-1.3.1-final-freeze','english-shell-1.3.1-final-freeze-pwa1','english-shell-1.3.1-final-freeze-pwa2','english-shell-1.3.1-final-freeze-pwa3','english-shell-1.3.1-final-freeze-pwa4','english-shell-1.3.1-final-freeze-pwa5','english-shell-1.3.1-final-freeze-pwa6','english-shell-1.3.1-final-freeze-pwa7','english-shell-1.3.1-final-freeze-pwa8','english-shell-1.3.1-final-freeze-pwa9','english-shell-1.3.1-final-freeze-pwa10'];for(const name of obsolete)await caches.delete(name);})()));
self.addEventListener('message',e=>{if(e.data?.type!=='CHECK_READY')return;e.waitUntil((async()=>{try{const c=await caches.open(SHELL);let ready=true;for(const path of FILES)if(!await c.match(new URL(path,BASE).href)){ready=false;break;}e.ports[0]?.postMessage({ready,version:BUILD});}catch{e.ports[0]?.postMessage({ready:false});}})());});
async function rangeResponse(r,range){if(!range)return r;const match=/^bytes=(\d+)-(\d*)$/.exec(range);if(!match)return r;const b=await r.blob(),start=Number(match[1]),end=match[2]?Math.min(Number(match[2]),b.size-1):b.size-1;if(start>end)return new Response(null,{status:416});return new Response(b.slice(start,end+1),{status:206,headers:{'Content-Type':r.headers.get('Content-Type'),'Content-Range':`bytes ${start}-${end}/${b.size}`,'Content-Length':String(end-start+1),'Accept-Ranges':'bytes'}});}
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.origin!==BASE.origin||!u.pathname.startsWith(BASE.pathname))return;const path=u.pathname.slice(BASE.pathname.length);
 e.respondWith((async()=>{if(path.startsWith('course/')||path.startsWith('units/')){try{const parts=path.split('/'),id=parts[0]==='units'?parts[1]:'U01',asset=parts.slice(parts[2]==='s'?4:parts[0]==='units'?2:1).join('/');const r=await registry.response(id,asset,parts[2]==='s'?parts[3]:null);return rangeResponse(r,e.request.headers.get('Range'));}catch{return new Response('这节课需要重新连接',{status:404});}}

  const c=await caches.open(SHELL),r=await c.match(new URL(path||'index.html',BASE).href);return r||fetch(e.request);
 })());
});
