import {storage} from './storage.js';
export async function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
export async function progressZip(db=storage,Zip=globalThis.JSZip){const zip=new Zip(),session=(await db.get('critical','session'))?.value;const critical=[];for await(const row of db.iterate('critical'))if(!row.id.startsWith('installed:')&&!row.id.startsWith('unit:'))critical.push(row);const events=[],review=[];for await(const r of db.iterate('events')){if(events.length>=10000)throw Error('本次记录超过备份上限。');events.push(r);}for await(const r of db.iterate('review'))review.push(r);const data={format:'LEARNER_STATE_BACKUP',version:1,session,critical,events,review,media_included:false};zip.file('progress.json',JSON.stringify(data));zip.file('version.json',JSON.stringify({format:'LEARNER_STATE_BACKUP',version:1}));return zip.generateAsync({type:'uint8array',compression:'DEFLATE'});}
export async function exportState(){const bytes=await progressZip();return downloadBlob(new Blob([bytes],{type:'application/zip'}),'LEARNER_STATE_BACKUP.zip');}
export async function restoreProgress(bytes,db=storage,Zip=globalThis.JSZip){if((bytes.size||bytes.byteLength)>8e6)throw Error('备份过大。');const zip=await Zip.loadAsync(bytes instanceof Blob?await bytes.arrayBuffer():bytes,{checkCRC32:true});if(Object.keys(zip.files).some(p=>!['progress.json','version.json'].includes(p)))throw Error('请选择学习进度备份。');const p=JSON.parse(await zip.file('progress.json').async('string'));if(p.format!=='LEARNER_STATE_BACKUP'||p.version!==1||!p.session?.session_id||!Array.isArray(p.events)||p.events.length>10000)throw Error('备份无效。');const existing=(await db.get('critical','session'))?.value;if(existing?.pilot_started_at)throw Error('此处已有学习进度，请在空白浏览器档案恢复，避免覆盖。');
 // Audio is deliberately absent. An interrupted utterance must be retried honestly.
 const s=p.session;s.recording_active=false;const pending=s.attempts.filter(a=>a.mode==='S'&&!a.result);for(const a of pending){a.audio_deleted=true;a.interrupted_restore=true;}
 s.attempts=s.attempts.filter(a=>!pending.includes(a));s.restore_interrupted_attempts=[...(s.restore_interrupted_attempts||[]),...pending];if(pending.length){s.screen=11;s.ended=false;s.final_evidence_settled=false;}
 const ops=[{store:'critical',value:{id:'session',value:s}},...p.critical.filter(x=>x.id!=='session'&&!x.id.startsWith('installed:')&&!x.id.startsWith('unit:')).map(value=>({store:'critical',value})),...p.events.map(value=>({store:'events',value})),...(p.review||[]).map(value=>({store:'review',value}))];await db.batch(ops);return {restored:true,interrupted_audio:pending.length};}
